// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMjewYxMGLEHPlpIVKrVvKr2gQn0c7s4Y',
    appId: '1:568779436910:web:93463584452656f52b477f',
    messagingSenderId: '568779436910',
    projectId: 'aiguitar-1553c',
    authDomain: 'aiguitar-1553c.firebaseapp.com',
    storageBucket: 'aiguitar-1553c.firebasestorage.app',
    measurementId: 'G-DW9FT7J80H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEaODI2nzNDXV6PvvY6NZpXSqVizxfASo',
    appId: '1:568779436910:android:1c054ec644995d942b477f',
    messagingSenderId: '568779436910',
    projectId: 'aiguitar-1553c',
    storageBucket: 'aiguitar-1553c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsCZ8dh-kQPT64TFkiNTnX8bSrIkqkES8',
    appId: '1:568779436910:ios:53c6da2603cae7a42b477f',
    messagingSenderId: '568779436910',
    projectId: 'aiguitar-1553c',
    storageBucket: 'aiguitar-1553c.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsCZ8dh-kQPT64TFkiNTnX8bSrIkqkES8',
    appId: '1:568779436910:ios:53c6da2603cae7a42b477f',
    messagingSenderId: '568779436910',
    projectId: 'aiguitar-1553c',
    storageBucket: 'aiguitar-1553c.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMjewYxMGLEHPlpIVKrVvKr2gQn0c7s4Y',
    appId: '1:568779436910:web:74d4315a9360da0b2b477f',
    messagingSenderId: '568779436910',
    projectId: 'aiguitar-1553c',
    authDomain: 'aiguitar-1553c.firebaseapp.com',
    storageBucket: 'aiguitar-1553c.firebasestorage.app',
    measurementId: 'G-S9Z6YZM9GS',
  );
}
